// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF1j0IfPIgz_RgBTsNFhcatfMwDiQb78s',
    appId: '1:366573246764:web:e93e693744e77df2c2f489',
    messagingSenderId: '366573246764',
    projectId: 'clo2-80b99',
    authDomain: 'clo2-80b99.firebaseapp.com',
    storageBucket: 'clo2-80b99.appspot.com',
    measurementId: 'G-5P2T59M3JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlx3_QXxKlmJ7ZySn9_NpBX2_VDRJ_IO4',
    appId: '1:366573246764:android:8e143aa0e08d5742c2f489',
    messagingSenderId: '366573246764',
    projectId: 'clo2-80b99',
    storageBucket: 'clo2-80b99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs0G5QOOpyKFDyF88m3Fl9FFASBnmvKOE',
    appId: '1:366573246764:ios:11863de71f967decc2f489',
    messagingSenderId: '366573246764',
    projectId: 'clo2-80b99',
    storageBucket: 'clo2-80b99.appspot.com',
    iosBundleId: 'com.example.clo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs0G5QOOpyKFDyF88m3Fl9FFASBnmvKOE',
    appId: '1:366573246764:ios:11863de71f967decc2f489',
    messagingSenderId: '366573246764',
    projectId: 'clo2-80b99',
    storageBucket: 'clo2-80b99.appspot.com',
    iosBundleId: 'com.example.clo2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF1j0IfPIgz_RgBTsNFhcatfMwDiQb78s',
    appId: '1:366573246764:web:143adcdcf3713a9ac2f489',
    messagingSenderId: '366573246764',
    projectId: 'clo2-80b99',
    authDomain: 'clo2-80b99.firebaseapp.com',
    storageBucket: 'clo2-80b99.appspot.com',
    measurementId: 'G-H4Q982FJHN',
  );
}
